### ISSUE TITLE
Getting Error when trying to run the app in

### ISSUE THREAD

**Issue by loquan** [simpulton/angular2-website-routes#6] opened 2016-06-20 11:37 UTC
Cannot find name 'require'
Cannot find name 'Promise'
Cannot find name 'Map'
Cannot find name 'Set'

**Comment by jdgarvey** [comment] 2016-06-20 16:21
@loquan thanks for the heads up! This is caused by Typings `1.x`; we have pushed a fix, so please pull the latest code and make sure that you have Typings `1.x` installed globally. Then run `npm i` and `typings i` and your problem should be resolved. Thanks!

**Closed by jdgarvey** 2016-06-20 16:21 UTC

**Comment by loquan** [comment] 2016-06-20 19:10
Thank you for the help and sharing all your info to the world.

1) I had to remove everything from my local build.  I might of corrupted it by trying to add things into it.

It work great now.  I am a newby in angular and node.   I programmed in php and basic javascript.  

LoQuan
--------------------------------------------
On Mon, 6/20/16, Jonathan Garvey <notifications@github.com> wrote:

 Subject: Re: [simpulton/angular2-website-routes] Getting Error when trying to run the app in (#6)
 To: "simpulton/angular2-website-routes" <angular2-website-routes@noreply.github.com>
 Cc: "LoQuan" <loquan@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Monday, June 20, 2016, 9:21 AM
 
 @loquan thanks for the
 heads up! This is caused by Typings 1.x; we
 have pushed a fix, so please pull the latest code and make
 sure that you have Typings 1.x installed
 globally. Then run npm i and typings
 i and your problem should be resolved. Thanks!
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
